name: CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: prod

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Detect dependency changes
        id: deps_changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            pyproject:
              - pyproject.toml

      - name: Deploy project files
        run: |
          cd /home/airflow
          cp ${{ github.workspace }}/pyproject.toml /home/airflow/
          cp -r ${{ github.workspace }}/dags /home/airflow/

      - name: Install dependencies
        run: |
          cd /home/airflow
          /home/airflow/.local/bin/poetry lock
          /home/airflow/.local/bin/poetry install --no-root

      - name: Restart Airflow
        if: steps.deps_changes.outputs.pyproject == 'true'
        run: |
          export XDG_RUNTIME_DIR=/run/user/$(id -u)
          systemctl --user restart airflow-webserver
          systemctl --user restart airflow-scheduler
