name: CI
on:
  push:
    branches:
      - feature/*
      - fix/*
  pull_request:
    branches:
      - master
    types:
      - opened

jobs:
  build:
    runs-on: test
    steps:
      - uses: actions/checkout@v5
      - name: list files
        run: ls -la $GITHUB_WORKSPACE
      - name: Build Docker
        run: docker build --progress=plain --no-cache -t dags:latest .

  test:
    needs: build
    runs-on: test
    steps:
      - name: Run tests
        run: docker run --rm dags:latest

  code_quality:
    needs: test
    runs-on: test
    steps:
      - name: install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install flake8
      - name: run flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --max-complexity=10 --max-line-length=120 --statistics

  cleanup:
    needs: test
    runs-on: test
    if: always()
    steps:
      - name: Cleanup
        run: |
          docker rm -f test_dags || true
          docker rmi dags:latest || true
