name: CI
on:
  push:
    branches:
      - feature/*
      - fix/*
  pull_request:
    branches:
      - feature/*
      - fix/*
      - master
    types:
      - opened
jobs:
  build:
    runs-on: test-runner
    steps:
      - name: checkout
        uses: actions/checkout@v5.0.0
      - name: build docker
        run: docker build -t . --progress=plain --no-cache --tag=dags:latest
  test:
    runs-on: test-runner
    steps:
      - name: test
        run: docker run dags:latest --name test_dags
  cleanup:
    runs-on: self-hosted
    if: always()
    steps:
      - name: cleanup
        run: docker rm

