name: CI
on:
  push:
    branches:
      - feature/*
      - fix/*
  pull_request:
    branches:
      - feature/*
      - fix/*
      - master
    types:
      - opened
jobs:
  build:
    runs-on: test
    steps:
      - name: checkout
        uses: actions/checkout@v5.0.0
      - name: build docker
        working-directory: ${{ github.workspace }}
        run: sudo docker build --progress=plain --no-cache -t dags:latest .
  test:
    needs: build
    runs-on: test
    steps:
      - name: test
        run: sudo docker run dags:latest --name test_dags
  cleanup:
    needs:
      - build
      - test
    runs-on: test
    if: always()
    steps:
      - name: cleanup
        run: sudo docker rm dags/test \
             sudo docker rmi dags:latest

