name: CI

on:
  push:
    branches:
      - feature/*
      - fix/*
      - codex/*

jobs:
  test:
    runs-on: test

    steps:
      - uses: actions/checkout@v5

      - name: Build Docker
        run: docker build --progress=plain -t dags:${{ github.sha }} .

      - name: Run tests
        run: docker run --rm dags:${{ github.sha }}

      - name: Cleanup
        if: always()
        run: |
          docker rm -f test_dags || true
          docker rmi dags:${{ github.sha }} || true

  code_quality:
    needs: test
    runs-on: test

    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies
        run: poetry install --no-root

      - name: Check code quality
        run: poetry run flake8 . --count --select=E,F --ignore=E226,E302,E305,E501 --show-source --statistics