name: CI
on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - feature/*
      - fix/*

jobs:
  build:
    runs-on: test
    steps:
      - uses: actions/checkout@v5
      - name: list files
        run: ls -la $GITHUB_WORKSPACE
      - name: Build Docker
        run: docker build --progress=plain --no-cache -t dags:latest .

  test:
    needs: build
    runs-on: test
    steps:
      - name: Run tests
        run: docker run --rm dags:latest

  code_quality:
    needs: test
    runs-on: test
    steps:
      - name: install dependencies
        run: poetry install --no-root
      - name: check code quality
        run: poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  cleanup:
    needs: test
    runs-on: test
    if: always()
    steps:
      - name: Cleanup
        run: |
          docker rm -f test_dags || true
          docker rmi dags:latest || true
